# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: spinnaker-jenkins-job-configurator
spec:
  template:
    spec:
      initContainers:
      - name: init-jenkins
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of Jenkins"; while ! nc -z jenkins-service.{{ .Release.Namespace }}.svc.cluster.local 8080; do sleep 1; printf "-"; done; echo -e "  >> Jenkins has started";']
      containers:
      - name: spin-jenkins-job-configurator
        image: appropriate/curl
        command: ["/bin/sh"]
        args: ["-c", "sh /spinnaker/run.sh"]
        env:
        - name: JENKINS_HOST
          value: "http://jenkins-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
        - name: JOB_NAME
          value: "job"
        volumeMounts: 
        - name: spinnaker-jenkins-job-conf
          mountPath: /spinnaker
      restartPolicy: Never
      volumes:
      - name: spinnaker-jenkins-job-conf
        configMap:
          name: spinnaker-jenkins-job-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-jenkins-job-conf
data:
  run.sh: |-
    cd spinnaker
    echo "Creating job"
    curl -X POST --fail "$JENKINS_HOST/createItem?name=$JOB_NAME" \
    --data-binary @scriptJobConfig.xml \
    --user {{ .Values.jenkins.username }}:{{ .Values.jenkins.password }} \
    -H "Content-Type:text/xml"
  scriptJobConfig.xml: |-
    <?xml version='1.0' encoding='UTF-8'?>
    <project>
      <actions/>
      <description></description>
      <logRotator class="hudson.tasks.LogRotator">
        <daysToKeep>10</daysToKeep>
        <numToKeep>500</numToKeep>
        <artifactDaysToKeep>-1</artifactDaysToKeep>
        <artifactNumToKeep>-1</artifactNumToKeep>
      </logRotator>
      <keepDependencies>false</keepDependencies>
      <properties>
        <hudson.security.AuthorizationMatrixProperty>
          <permission>hudson.model.Item.Delete:api_team</permission>
          <permission>hudson.model.Item.Read:api_team</permission>
          <permission>hudson.model.Run.Delete:api_team</permission>
          <permission>hudson.model.Item.Workspace:api_team</permission>
          <permission>hudson.model.Item.Build:api_team</permission>
          <permission>hudson.scm.SCM.Tag:api_team</permission>
          <permission>hudson.model.Item.Configure:api_team</permission>
          <permission>hudson.model.Run.Update:api_team</permission>
          <permission>hudson.model.Item.Discover:anonymous</permission>
        </hudson.security.AuthorizationMatrixProperty>
        <hudson.plugins.buildblocker.BuildBlockerProperty plugin="build-blocker-plugin@1.7.1">
          <useBuildBlocker>true</useBuildBlocker>
          <blockLevel>UNDEFINED</blockLevel>
          <scanQueueFor>DISABLED</scanQueueFor>
          <blockingJobs>STASH_MAINTENANCE_DOWNTIME</blockingJobs>
        </hudson.plugins.buildblocker.BuildBlockerProperty>
        <com.chikli.hudson.plugin.naginator.NaginatorOptOutProperty plugin="naginator@1.15">
          <optOut>false</optOut>
        </com.chikli.hudson.plugin.naginator.NaginatorOptOutProperty>
        <hudson.model.ParametersDefinitionProperty>
          <parameterDefinitions>
            <hudson.model.StringParameterDefinition>
              <name>TASK_ID</name>
              <description>Unique Task Id generated by Spinnaker</description>
              <defaultValue>0</defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>SCRIPT_PATH</name>
              <description>Path to the folder hosting the scripts</description>
              <defaultValue>.</defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>COMMAND</name>
              <description>Executable script and parameters</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>IMAGE_ID</name>
              <description>The image ID for this region based on the AMI Spinnaker is deploying</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>REGION_PARAM</name>
              <description>The region the Spinnaker deployment is running against</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>ENV_PARAM</name>
              <description>Environment Spinnaker is running against</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>CLUSTER_PARAM</name>
              <description>The cluster Spinnaker is deploying to</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>CMC</name>
              <description>The CMC this deployment is associated with</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>CONTEXT</name>
              <description>The parameters available to this task</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
            <hudson.model.StringParameterDefinition>
              <name>REPO_URL</name>
              <description>git repository url.</description>
              <defaultValue></defaultValue>
            </hudson.model.StringParameterDefinition>
          </parameterDefinitions>
        </hudson.model.ParametersDefinitionProperty>
        <com.gmail.ikeike443.PlayAutoTestJobProperty plugin="play-autotest-plugin@0.0.12"/>
        <com.sonyericsson.rebuild.RebuildSettings plugin="rebuild@1.25">
          <autoRebuild>false</autoRebuild>
          <rebuildDisabled>false</rebuildDisabled>
        </com.sonyericsson.rebuild.RebuildSettings>
        <hudson.plugins.disk__usage.DiskUsageProperty plugin="disk-usage@0.25"/>
      </properties>
      <scm class="hudson.plugins.git.GitSCM" plugin="git@2.4.0">
        <configVersion>2</configVersion>
        <userRemoteConfigs>
          <hudson.plugins.git.UserRemoteConfig>
            <name>apidaemon</name>
            <url>$REPO_URL</url>
          </hudson.plugins.git.UserRemoteConfig>
        </userRemoteConfigs>
        <branches>
          <hudson.plugins.git.BranchSpec>
            <name>master</name>
          </hudson.plugins.git.BranchSpec>
        </branches>
        <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
        <browser class="hudson.plugins.git.browser.Stash">
          <url></url>
        </browser>
        <submoduleCfg class="list"/>
        <extensions>
          <hudson.plugins.git.extensions.impl.PerBuildTag/>
          <hudson.plugins.git.extensions.impl.WipeWorkspace/>
        </extensions>
      </scm>
      <canRoam>false</canRoam>
      <disabled>false</disabled>
      <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
      <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
      <jdk>Oracle JDK8</jdk>
      <triggers/>
      <concurrentBuild>true</concurrentBuild>
      <builders>
        <hudson.plugins.descriptionsetter.DescriptionSetterBuilder plugin="description-setter@1.10">
          <regexp></regexp>
          <description>TASK=${TASK_ID} REGION=${REGION_PARAM} ENV=${ENV_PARAM} CLUSTER=${CLUSTER_PARAM} IMAGE=${IMAGE_ID} CMC=${CMC} ${SCRIPT_PATH}/${COMMAND} ${CONTEXT}</description>
        </hudson.plugins.descriptionsetter.DescriptionSetterBuilder>
        <hudson.tasks.Shell>
          <command># To run groovy scripts in this stage, you need to add groovy to your path:
    # export PATH=$PATH:/PATH/TO/GROOVY/bin
    # To add support for grapes, you need to install the package and add this flag,
    # pointing to the correct grape root directory.
    # export JAVA_OPTS=&apos;-Dgrape.root=${WORKSPACE}/.groovy/grape&apos;
    echo ${TASK_ID}
    sh ${SCRIPT_PATH}/${COMMAND}</command>
        </hudson.tasks.Shell>
      </builders>
      <publishers>
        <hudson.tasks.ArtifactArchiver>
          <artifacts>*.properties, *.json, *.yml</artifacts>
          <allowEmptyArchive>true</allowEmptyArchive>
          <onlyIfSuccessful>false</onlyIfSuccessful>
          <fingerprint>false</fingerprint>
          <defaultExcludes>true</defaultExcludes>
        </hudson.tasks.ArtifactArchiver>
      </publishers>
      <buildWrappers>
        <EnvInjectBuildWrapper plugin="envinject@1.91.4">
          <info>
            <propertiesContent>PYTHONUNBUFFERED=1
    P4USER=rolem</propertiesContent>
            <loadFilesFromMaster>false</loadFilesFromMaster>
          </info>
        </EnvInjectBuildWrapper>
      </buildWrappers>
    </project>
