# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: 'wso2/kubernetes-pipeline-jenkins:latest'
wso2Username: ""
wso2Password: ""

# Admin credentials of jenkins instance to be created
jenkins:
  username: admin
  password: admin

registry:
  server: 'https://index.docker.io/v1/'
  username: <REGISTRY_USERNAME>
  password: <REGISTRY_PASSWORD>
  email: <REGISTRY_EMAIL>
  address: index.docker.io

github:
  username: <GITHUB_USERNAME>
  password: <GITHUB_PASSWORD>

# Values for Spinnaker chart
spinnaker:
  halyard:
    spinnakerVersion: 1.15.2
    # image:
    #   tag: 1.20.2
    additionalScripts:
      create: true
      data:
        enable_ci.sh: |-
          echo "Configuring jenkins master"
          USERNAME="admin"
          PASSWORD="admin"
          $HAL_COMMAND config ci jenkins enable
          echo $PASSWORD | $HAL_COMMAND config ci jenkins master edit master --address http://jenkins-service.{{ .Release.Namespace }}.svc.cluster.local:8080 --username $USERNAME --password || echo $PASSWORD | $HAL_COMMAND config ci jenkins master add master --address http://jenkins-service.{{ .Release.Namespace }}.svc.cluster.local:8080 --username $USERNAME --password
          $HAL_COMMAND config features edit --pipeline-templates true
  ingress:
    enabled: true
    host: spinnaker
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: '-tls'
        hosts:
          - domain.com
  ingressGate:
    enabled: true
    host: gate.spinnaker
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
     - secretName: -tls
       hosts:
         - domain.com

kibana:
  nameOverride: "kibana"
  elasticsearchHosts: "http://wso2-elasticsearch-master:9200"
  ingress:
    enabled: true
    hosts:
      - kibana
    tls:
      - hosts:
          - kibana
          
elasticsearch:
  minimumMasterNodes: 1
  replicas: 1
  imageTag: 7.3.0
  clusterName: wso2-elasticsearch
  persistence:
    enabled: false
  esJavaOpts: -Xms512m -Xmx512m

prometheus-operator:
  kubeEtcd: # Disable Etcd metrics
    enabled: false
  kubeControllerManager: #Disble KubeController Metrics
    enabled: false
  kubeScheduler: # Disable Scheduler metrics
    enabled: false
  alertmanager:  # Disable Alert Manager
    enabled: false
  kubeApiServer:
    enabled: false
  coreDns:
    enabled: false
  kubeProxy:
    enabeld: false
  prometheus:
    prometheusSpec:
      image:
        tag: v2.9.2
  grafana:
    image:
      tag: 6.1.6
    adminPassword: "admin"
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana

nodeExporter:
  enabled: false
kubeStateMetrics:
    enabled: false

prometheus-blackbox-exporter:
  serviceMonitor:
    enabled: true
  config: 
    modules:
      http_2xx:
        prober: http
        http:
          tls_config:
            insecure_skip_verify: true
